### ISSUE TITLE
Int conversion

### ISSUE THREAD

**Issue by pyreta** [zipmark/zipmark-code-challenge#15]
Right now my parsing is using int conversion on many of the fields which cut off any leading zero's.  The routing number as of right now does not include the first zero.  I need to change the conversion to fix this.

**Comment by pyreta** [comment]
Fixed conversion.

**Comment by mecampbellsoup** [comment]
@pyreta you should treat the routing numbers as strings and not integers

**Comment by pyreta** [comment]
@mecampbellsoup yes I removed all unnecessary int conversion.
